# Generated by Django 2.1.3 on 2019-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_auto_20190107_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
